# Generated by Django 4.2.7 on 2025-10-21 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0002_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Img',
        ),
    ]
