# Generated by Django 4.2.7 on 2026-01-06 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0003_delete_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textright',
            options={'verbose_name': 'Ong taraf ozgarish'},
        ),
    ]
