# Generated by Django 4.2.7 on 2026-01-06 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0004_alter_textright_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textleft',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='textright',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
